<!--D-WEB Ellen e André 2°INF-->
<!--Algumas páginas ainda vão ser completadas-->
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/png" href="/TGS_FINAL/images/icones/logo.png"/>
        <link rel="stylesheet" href="/TGS_FINAL/css/style_space.css"/>
        <title>TGS - The Game Space</title>

    </head>

    <body class="fundo">

        <div class="backwrap gradient">
            <div class="back-shapes">
                <!-- All this img tags was autogenerated by custom written js tool -->
                <span class="floating circle" style="top:66.59856996935649%;left:13.020833333333334%;animation-delay:-0.9s;"></span>
                <span class="floating triangle" style="top:31.46067415730337%;left:33.59375%;animation-delay:-4.8s;"></span>
                <span class="floating cross" style="top:76.50663942798774%;left:38.020833333333336%;animation-delay:-4s;"></span>
                <span class="floating square" style="top:21.450459652706844%;left:14.0625%;animation-delay:-2.8s;"></span>
                <span class="floating square" style="top:58.12053115423902%;left:56.770833333333336%;animation-delay:-2.15s;"></span>
                <span class="floating square" style="top:8.682328907048008%;left:72.70833333333333%;animation-delay:-1.9s;"></span>
                <span class="floating cross" style="top:31.3585291113381%;left:58.541666666666664%;animation-delay:-0.65s;"></span>
                <span class="floating cross" style="top:69.96935648621042%;left:81.45833333333333%;animation-delay:-0.4s;"></span>
                <span class="floating circle" style="top:15.117466802860061%;left:32.34375%;animation-delay:-4.1s;"></span>
                <span class="floating circle" style="top:13.074565883554648%;left:45.989583333333336%;animation-delay:-3.65s;"></span>
                <span class="floating cross" style="top:55.87334014300306%;left:27.135416666666668%;animation-delay:-2.25s;"></span>
                <span class="floating cross" style="top:49.54034729315628%;left:53.75%;animation-delay:-2s;"></span>
                <span class="floating cross" style="top:34.62717058222676%;left:49.635416666666664%;animation-delay:-1.55s;"></span>
                <span class="floating cross" style="top:33.19713993871297%;left:86.14583333333333%;animation-delay:-0.95s;"></span>
                <span class="floating square" style="top:28.19203268641471%;left:25.208333333333332%;animation-delay:-4.45s;"></span>
                <span class="floating circle" style="top:39.7344228804903%;left:10.833333333333334%;animation-delay:-3.35s;"></span>
                <span class="floating triangle" style="top:77.83452502553627%;left:24.427083333333332%;animation-delay:-2.3s;"></span>
                <span class="floating triangle" style="top:2.860061287027579%;left:47.864583333333336%;animation-delay:-1.75s;"></span>
                <span class="floating triangle" style="top:71.3993871297242%;left:66.45833333333333%;animation-delay:-1.25s;"></span>
                <span class="floating triangle" style="top:31.256384065372828%;left:76.92708333333333%;animation-delay:-0.65s;"></span>
                <span class="floating triangle" style="top:46.47599591419816%;left:38.90625%;animation-delay:-0.35s;"></span>
                <span class="floating cross" style="top:3.4729315628192032%;left:19.635416666666668%;animation-delay:-4.3s;"></span>
                <span class="floating cross" style="top:3.575076608784474%;left:6.25%;animation-delay:-4.05s;"></span>
                <span class="floating cross" style="top:77.3237997957099%;left:4.583333333333333%;animation-delay:-3.75s;"></span>
                <span class="floating cross" style="top:0.9193054136874361%;left:71.14583333333333%;animation-delay:-3.3s;"></span>
                <span class="floating square" style="top:23.6976506639428%;left:63.28125%;animation-delay:-2.1s;"></span>
                <span class="floating square" style="top:81.30745658835546%;left:45.15625%;animation-delay:-1.75s;"></span>
                <span class="floating square" style="top:60.9805924412666%;left:42.239583333333336%;animation-delay:-1.45s;"></span>
                <span class="floating square" style="top:29.009193054136876%;left:93.90625%;animation-delay:-1.05s;"></span>
                <span class="floating square" style="top:52.093973442288046%;left:68.90625%;animation-delay:-0.7s;"></span>
                <span class="floating square" style="top:81.51174668028601%;left:83.59375%;animation-delay:-0.35s;"></span>
                <span class="floating square" style="top:11.542390194075587%;left:91.51041666666667%;animation-delay:-0.1s;"></span>
            </div>
        </div>

        <?php include_once('header.php'); ?>

        <main>

            <div class="separacao">
                <section class="secao princ">
                    <h1 class="titulo" style="color:#DAADFF" id="titulo_icon">  <div>The Game Space </div> <img id="icon_sp" src="/TGS_FINAL/images/icones/icons8-playstation-buttons-50.png"> </h1> 
                </br>

                    <div class="meio_s">
                        <div class="slider">
        
                            <div class="slides">
                                <input type="radio" name="radio-btn" id="radio1">
                                <input type="radio" name="radio-btn" id="radio2">
                                <input type="radio" name="radio-btn" id="radio3">
                    
                                <div class="slide first">
                                    <!--imagens-->
                                    <div class="container">
                                        <img src="/TGS_FINAL/images/imagens_carrossel/1.jpg" class="size">
                                    </div>
                                </div>
                    
                                <div class="slide second">
                                    <div class="container">
                                        <img src="/TGS_FINAL/images/imagens_carrossel/2.jpg" class="size">
                                    </div>
                                </div>
                    
                                <div class="slide third">
                                    <div class="container">
                                        <img src="/TGS_FINAL/images/imagens_carrossel/3.jpg" class="size">
                                    </div>
                                </div>
                    
                                <!--navegação automática-->
                                <div class="navigation-auto">
                                    <div class="auto-btn1"></div>
                                    <div class="auto-btn2"></div>
                                    <div class="auto-btn3"></div>
                                </div>
                    
                            </div>
                    
                            <!--navegação manual-->
                            <div class="navigation-manual">
                                <label for="radio1" class="manual-btn"></label>
                                <label for="radio2" class="manual-btn"></label>
                                <label for="radio3" class="manual-btn"></label>
                            </div>
                    
                        </div>
                    </div>
                    </br>


                    <p class="sp_texto_comum">
                        Sejam muito bem vindos ao <i><strong>The Game Space</strong></i>, para um rápido entendimento do site, observe os tópicos a seguir:
                    </p>
                    </br>
                    <h3 class="subtitulo"><b>1. O Intuito</b></h3>
                    <p class="sp_texto_comum espaco">O intuito do site, como o próprio nome já dá uma dica, é preparar reviews de jogos,
                        em que poderemos ajudar as pessoas a escolher algum jogo do seu gosto,
                        sem que ele seja de uma plataforma específica, utilizando nossas recomendações e opiniões.
                    </p>
                    </br>
                    <h3 class="subtitulo"><b>2. O Público Alvo</b></h3>
                    <p class="sp_texto_comum espaco">Apesar dos jogos terem se popularizado muito entre os jovens,
                         não possuí­mos um público alvo bastante especí­fico, podendo esse, variar de acordo com a review.</p>
                    </br>
                    <h3 class="subtitulo"><b>3. Os tipos de jogos comentados no site</b></h3>
                    <p class="sp_texto_comum espaco">Os tipos jogos, assim como o público alvo das reviews, podem variar, seja jogos do tipo RPG, Plataforma, Estratégia, Simulação, entre outros</p>
                    </br>
                    <h1 class="titulo">Como encontrar o seu estilo/tipo de jogo?</h1>
                    <div class="img_posi">
                        <img src="/TGS_FINAL/images/boneco no computador.png">
                    </div>     
                    </br>
                    </br>
                    <p class="sp_texto_comum">
                        Nós sabemos como pode ser complicado às vezes, encontrar algum jogo que seja cativante
                        e interessante, por isso é muito importante você saber qual é o seu estilo, pois assim
                        você consiguirá encontrar mais facilmente o seu jogo tão desejado. Então segue aí­ algumas
                        dicas para você encontrá-lo:
                    </p>
                    </br>
                    <h3 class="subtitulo">Observe se você prefere mais jogos físicos ou jogos online</h3>
                    <p class="sp_texto_comum espaco">
                        Para pessoas que já estejam acostumadas com a tecnologia atual essa pergunta pode ser bem fácil
                        , porém os jogos físicos como UNO, xadrez, dama, Monopoly, entre outros, podem ser uma boa opção
                        para aqueles que querem ter um um contato mais direto com os amigos.
                    </p>
                    </br>
                    <h3 class="subtitulo">Qual sua época preferida de jogos?</h3>
                    <p class="sp_texto_comum espaco">
                        Existem pessoas que estão acostumados à jogos de certas épocas, seja pela estética, jogabilidade e/ou até o tema
                        dos jogos dessa época, mas também há pessoas que não se importam muito com o tempo em que foi criado um jogo, se
                        importando assim, apenas se o jogo realmente é bom para ela.
                    </p>
                    </br>
                    <h3 class="subtitulo">Um jogo tem que ser de qual nível para você?</h3>
                    <p class="sp_texto_comum espaco">
                        Para você, qual deve ser o nível de dificuldade de um jogo? Você gosta de quebrar muito a cabeça? Prefere algo mais
                        casual ou calmo? Saber disso é bastante importante para que você não se estresse com algum jogo que não se encaixe no seu perfil.
                    </p>
                    </br>
                    <h3 class="subtitulo">Quando tempo você possui para poder jogar?</h3>
                    <p class="sp_texto_comum espaco">
                        Saber gerenciar o tempo é uma tarefa de extrema importância, principalmente para atividades cotidianas como os estudos e trabalho, 
                        mas também sabemos como é importante ter um momento de lazer, no caso, com os jogos. Saber mais ou menos a quantidade de tempo que você tem
                        vai te ajudar a encontrar jogos dentro do intervalo que você possui. Por exemplo, caso você não tenha muito tempo para jogar, é recomendado
                        você achar um jogo com histórias curtas, de fácil tutorial, e que não necessite de uma jogabilidade contínua (ou seja, você pode continuar a jogar mais tarde).
                    </p>
                    </br>
                    <h3 class="subtitulo">O que você realmente busca com o jogo?</h3>
                    <p class="sp_texto_comum espaco">
                        O principal: qual o seu intuito ao jogar? Se divertir? Aprender algo novo? Conversar com os amigos? Relaxar? Participar de campeonatos? Ou tudo isso junto?
                        São perguntas interessantes de se fazer para você saber o que realmente quer em um jogo, observar se a estética, jogabilidade, estilo, linguagem, entre outros
                        aspectos te agradam.
                    </p>
                    </br>
                    
                </section>
    
                <aside class="secao secun">
                    <h4 class="sec_jog">JOGOS</h4>
                    <ul class="sec_list">
                        <li><a href="index.html">Gêneros</a></li>
                        <li><a href="index.html">Desenvolvedores</a></li>
                        <li><a href="index.html">Classificação</a></li>
                    </ul>
                </aside>
            </div>

            <img src="/TGS_FINAL/images/icones/logo.png" class="manete_logo" >
            
        </main>

        <?php include_once('footer.php') ?>
        
        <script src="/TGS_FINAL/js/js2.js"></script>
    </body>

</html>